#!/bin/bash
./build
if [ $? -ne 0 ]
then
	echo "failed building parser from grammar"
	exit 1
fi
echo "testing basic.polh"; ./main tests/basic.polh;
echo "testing expression_basic.polh"; ./main tests/expression_basic.polh
